### ISSUE TITLE
Ошибки с JSON при обращении к dropdown'у на токенах

### ISSUE THREAD

**Issue by ghost** [bibaev/code-completion-evaluation#113]
Во многих html-отчетах по отдельным файлам не работает dropdown по клику на токен.
Консоль браузера выдает, например, следующее:
```
Uncaught SyntaxError: Unexpected token 
 in JSON at position 74667
    at JSON.parse (<anonymous>)
    at AbstractQuery.java.html:180
```
Соответсвующие `java`-файл и `JSON` в архиве [ArrayQuery.zip](https://github.com/bibaev/code-completion-evaluation/files/3550348/ArrayQuery.zip)

**Comment by bibaev** [comment]
Вроде больше не встречалось. Видимо пофиксили в одном из больших изменений
