### ISSUE TITLE
Переключаться между длиной префикса в html-отчете по файлу

### ISSUE THREAD

**Issue by ghost** [bibaev/code-completion-evaluation#114]
Сейчас при запуске на нескольких длинах префикса в html-отчетах по файлу раскраска токенов и их dropdown'ы соответствуют нулевому префиксу. Нужна возможность прямо на этой странице выбирать для какой длины префикса отрисовывается отчет с соответствующей этому префиксу раскраской и содержанием dropdown'ов.

На скриншоте приведен фрагмент отчета после запуска с префиксами длины 0, 1 и 2, но посмотреть можно только инфу про нулевой префикс.
![image](https://user-images.githubusercontent.com/52570124/63848657-ea063c80-c998-11e9-9a78-20da00476c37.png)

**Comment by AlexeyKalina** [comment]
В данном конкретном случае на других префиксах completion и не вызывался. После того, как на нулевом префиксе в подсказках появился нужный токен, он был выбран и выполнение перешло к следующему токену.

Но если бы нужных подсказок не было, то действительно completion отработал бы на всех трех префиксах, а в отчете отображаю только последний.
