### ISSUE TITLE
Change default: do not include files without sessions to HTML reports

### ISSUE THREAD

**Issue by bibaev** [bibaev/code-completion-evaluation#155]
Мне кажется, что по умолчанию при построении отчета логично пропускать файлы, в которых мы не нашли подходящих мест, чтобы вызвать completion. Эта информация скорее полезна для диагностики, чем для самого отчета. Поэтому её можно написать в консоль, либо в какой-нибудь вспомогательный файл, но не в html с отчетом. При этом, можно оставить возможность включить registry, который будет строить репорты с такой информацией.

@AlexeyKalina, @stoyanovskiy239 Как вы считаете?

**Comment by stoyanovskiy239** [comment]
Как вариант – чекбокс "Show 0 session files", по умолчанию unchecked
