### ISSUE TITLE
Add diff column into the reports

### ISSUE THREAD

**Issue by bibaev** [bibaev/code-completion-evaluation#161]
It would be nice to find out that metrics are different while comparing two evaluation reports. think it would be useful to have an ability to add columns with difference between two metrics for evaluating. These columns could be auto-generated and hidden by default

**Comment by stoyanovskiy239** [comment]
Sounds nice. What about reports with 3+ evaluations? Adding diff columns would make those a bit too messy. I suggest implementing this feature for report with 2 evaluations only.

**Comment by bibaev** [comment]
Let's implement the feature for 2 evaluations only
