### ISSUE TITLE
Изменить структуру директорий с отчетами

### ISSUE THREAD

**Issue by bibaev** [bibaev/code-completion-evaluation#27]
Сейчас отчеты по всем файлам валятся в одну папку, создавая по папке на каждый файл. Если в одном запуске было несколько файлов и в директории уже что-то лежит, то понять какие именно файлы нужно смотреть очень неудобно. Предлагаю сделать такую скруктуру папок для отчетов:
```
reports/
  - 2019-04-27_12-20-20/
    - res/
      - Main.java.js
      - Util.java.js
    - Main.java.html
    - Util.java.html
  - 2019-04-27_12-30-25/
    - res/
      - Main.java.js
    - Main.java.html
```
Тогда мы можем предложить открыть сразу папку для последнего сгененрированного отчета.

**Comment by AlexeyKalina** [comment]
Согласен, что можно создавать внешнюю папку с датой для нового запуска, но для файлов внутри все равно нужна какая-то добавка к имени файла - с тем же временем, как вариант. Т.к. в пределах одного запуска может быть несколько файлов с одним именем.

**Comment by bibaev** [comment]
Согласен про добавку, но лучше не использовать время. Во-первых время с точностью до секунды может все-равно совпасть у жвух файлов. Во-вторых оно будет неинформативно - эта же информация есть в имени папки. Можно использовать один из таких вариантов
* повторить структуру папок, начиная c ближайшего общего предка
* записывать относительный путь от ближайшего общего предка к файлу в имя через точку - тогда получим что-то похожее на java package
* для файлов с одинаковым именем писать порядковый номер.
