### ISSUE TITLE
Пропавшие `System.` ?

### ISSUE THREAD

**Issue by bibaev** [bibaev/code-completion-evaluation#83]
На скриншоте внутри `for` есть `System.out.println(...)`, а после тела цикла похожие использования но уже без `System.`. Это такой код и был, или мы что-то потеряли по пути?
![image](https://user-images.githubusercontent.com/7608535/62346179-d2ed3f80-b4fd-11e9-925a-117087b145da.png)

**Comment by AlexeyKalina** [comment]
[Такой код](https://github.com/javaee-samples/javaee7-samples/blob/master/jaxrs/invocation/src/main/java/org/javaee7/jaxrs/invocation/TestServlet.java). Это разные `out`.
