### ISSUE TITLE
Записывать логи в один файл в процессе интерпретации экшенов

### ISSUE THREAD

**Issue by AlexeyKalina** [bibaev/code-completion-evaluation#99]
А потом нарезать на два файла с учетом сессий

**Comment by bibaev** [comment]
Сейчас мы пишем файлы в формате `N.log` при этом не гарантируется, что если сессия не поместилась в файл `n.log`, то она будет в `n+1.log`. Она вполне может оказаться и в `n+5.log`. Хотелось бы гарантировать, что строки, относящийся к одной сессии будут идти последовательно в итоговом файле.
